name = "UrbanCanopy"
uuid = "d4eb39aa-53a3-45de-9c50-84bd270bed3a"
version = "0.1.0"
authors = ["EarthSciML authors and contributors"]

[deps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
DynamicQuantities = "1"
ModelingToolkit = "10"
OrdinaryDiffEqDefault = "1"
TestItemRunner = "1.1.0"
julia = "1"

[extras]
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "OrdinaryDiffEqDefault", "TestItemRunner"]
